#!/usr/bin/env lua 

local socket = require("socket")

local host = "www.google.com"
local file = "/"

local sock = assert(socket.connect(host, 80))
sock:send("GET" .. file .. " HTTP/1.0\r\n\r\n")
repeat 
	-- receiving chunk in 1KB unit
	local chunk, status, partial = sock:receive(1024)
	print (chunk or partial)
until status ~= "closed" 

-- close tcp connection
sock:close()
